feeds:
  - https://techcrunch.com/feed/
  - https://japan.cnet.com/rss/all.rdf
  - https://openai.com/blog/rss/
similarity_threshold: 0.72
per_feed_limit: 10
archive_days: 7
emit_jp: true
emit_en: false   # ← ENは無効
